name: Build st in Debian Stable Container

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest  # This is to run the GitHub Actions 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name:  install dependecies
      run: |
       bash build.sh
       upload=$(realpath busybox)
       echo "FILE1=${upload}" >> $GITHUB_ENV 

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
          tag_name: 1.0.0
          files: |
              ${{ env.FILE1 }}
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}       
       
       
      
